= Federal Land Acquistion

== Obtaining Land in the Public Domain 

The steps in purchasing federal land are described  in <<hone-book, Land & Property Research in the United States,
2nd edition, by E. Wade Hone>>. Chapter nine **Records Generated by Federal Lands** describes each of the the steps
involved in purchasing land in the public domain and the documents that were generated. 

Step one was the **application**:

[quote, page 110]
.Step one in Land Acquistion: the application
____
When a desired tract or parcel of land was located in the public domain an individual first needed to make an **application**
or entry for that particular segment of land...Sometimes payment itself was considered adequate for successful application.
____

Auctions were usually held when an area first opned for public sale. Soon afterward, local land offices opened for business to
where settlers applied on a "first come, first serve" basis for each segment of land.

In order to purchase land from the federal government, an applicant had to be **native-born** or at least **declared an intention to
become a citizen of the United States** (although this requirement did not apply to military bounty land warrants and some
preemption and private land claims).

The Land Act of 1820 discontinued credit sales and required cash payment in full. After full payment was made a receipt issued. 

[quote, page 111]
.Step two in Land Acquistion under the Land Act of 1820: Cash payment in full and issuance of a receipt.
____
Once the application was completed, cash was paid, or appropirate arrangements made for credit and a **receipt** was issued.
____


After payment was made....

TODO: complete the steps.


[bibliography]
== References

* [[[hone-book]]] Hone, E. Wade, _Land & Property Research in the United States_ (Provo Utah, Ancestry Publishing, 1997)
* [[[page-110]]] _Ibid_, page 110 
* [[[page-111]]] _Ibid_, page 111 
