= Land Acts

These are some of the land acts that are relevant to the purchase of federal
land in Indiana in the 19^th^ century.

== Land Ordinace of 1785

The 1785 Ordinance provided for the survey and sale of this land in the Public Land States
in tracts of no less than 640 acres, equivalent to a Section, which is one square mile.
This was the beginning of the cash-entry system for federal lands. The Land Ordinance of
1785 also introduced federal support for public schooling, granting Section 16 (one square
mile) of every township to be used “for the maintenance of public schools within said
township.

== Harrison Land Act of 1800

The Land Act of 1800 reduced the minimum purchasable unit of land from 640 acres to 320
acres at a minimum cost of $2 per acre. It also introduced the option of credit sales to
encourage land sales. Land purchased under the Harrison Land Act of 1800 could be paid for
by putting down half of the required payment upfront and the remainder in equal
installments over a period of four years.

== Land Act of 1820

The Land Act of 1820, also referred to as the 1820 Sale Act, reduced the price of federal
land (Northwest Territory and Missouri Territory) to $1.25 acre, with a minimum purchase
of 80 acres and downpayment of $100. The act also granted squatters the right to preempt
these conditions and purchase the land even more cheaply if they had made improvements to
the land such as the building of homes, fences, or mills. This act eliminated credit
sales, the purchase of public land in the United States on credit.

== Preemption Acts of 1841

This act allow "squatters" preemptive rights to purchase land in the public domain on which
they were living. The requirements were: 

* The applicant was the head of a family, a widow or single man over the age of 21 years

* The applicant was an American citizen or intended to become a citizen 

* The applicant had, since June 1, 1840, made a settlement in person upon the public lands

* The lands settled upon were no longer under Indian title 

* The lands settled upon had been surveyed 

* The applicant had erected a dwelling upon the parcel at issue 

* The applicant was not requesting more than 160 acres of land 

* The applicant had submitted payment of $1.25 per acre to the GLO Registrar 
