= Social-Historical Background

== Books

* Schmöe, Hermann. _800 Jahre Kirchspiel Petzen: Berenbusch, Evesen, Nordholz, Petzen, Röcke 1181-1981_ (English title
translation: "800 Years of the Parish of Petzen : Berenbusch, Evesen, Nordholz, Petzen, Röcke 1181–1981"), Library holdings:
Niedersächsische Landesbibliothek, Hannover]
* link:https://www.gutenberg.org/ebooks/33818[Pictures of German Life in the
Eighteenth and Nineteenth Centuries, vol. 1], Gustav Freytag, Translated by Mrs. Malcolm, on Gutenberg.org
* link:https://www.gutenberg.org/ebooks/33819[Pictures of German Life in the
Eighteenth and Nineteenth Centuries, vol. 2], Gustav Freytag, Translated by Mrs. Malcolm, on Gutenberg.org

== de.wikipedia.org

https://de.wikipedia.org/wiki/Schaumburg-Lippe[Schaumburg-Lippe].

== Articles

link:https://doi.org/10.1177/036319909201700205[From Peasant Society to Class Society: Some Aspects of Family and
Class in a Northwest German Protoindustrial Parish, 17th-19th Centuries], Journal of Family History, Vol. 17, Issue 2, April 1992.


