= Bios of Founders

The link:https://www.immanueldecatur.org/Church_History.html[brief history] of Immanuel Lutheran states:

[quote, Brief History]
____
The first church, built of logs, was begun in 1851 by the half dozen pioneers here at the time,
but the structure was completed and dedicated in 1855.
____

Biographies of the founders were written in old German script, the Gothic style of handwritten script that was used in Germany until WWII
when German schools introduced the current latin-based handwriting. Two founders do not have biographies:

* Jacob Fridrich Höringer
* Christain Wilhelm Fells

Might these two individuals may have moved away before any of their offspring was old enough to remain in Union township--or at least nearby
in Adams County--and pass on the details of their life are missing? Neither of these two individuals is mentioned in
the xref:https://dsfafa[brief history] of Immanuel Lutheran.

The precise dates of their departures from Union township has not been researched. We do know (todo: add the source) ... and ... went to Thayer County, Nebraska, and ... to Van Wert, Ohio.... 

todo: change the sref below a Google Drive link--once I have organized my PC genealogy files.
