register_shortnames:
  - petzen1a
  - petzen1b
  - petzen2
  - frille1
  - frille2
place_names:
   - locality: &unknown Unknown
     alias: self 
   - locality: &petzen Petzen
     alias: self 
   - locality: &nordholz Nordholz
     alias: self 
   - locality: &berenbusch Berenbusch
     alias: self 
   - locality: &evesen Evesen
     alias: self 
   - locality: &baerenbusch Bärenbusch
     alias: *berenbusch
