#!/usr/bin/env bash
rm -rf public
npx antora local-playbook.yml 
cp  css/kurt-customizations.css public/_/css/
cp  fonts/* public/_/font/
rm -rf /var/www/krueckeberg.org/docs/*
cp -r public /var/www/krueckeberg.org/docs
chown -R root:www-data /var/www/krueckeberg.org/docs
chmod -R g+w /var/www/krueckeberg.org/docs
