= TODO

== For the Pedigree of Carl Friedrich Krückeberg (born 1807) and Johann Heinrich Krückeberg
* Write up a explanation and the significance of the Nachträge.
* confirm the in most recent Nachträge:
** xref:petzen:petzen-band2-image125-entry31.adoc[1812 Carloline Dorothee Krückeberg Baptism]
** xref:petzen:petzen-band2-image27.adoc[1812 Philippine Caroline Christine Krückeberg Marriage]
** xref:petzen:petzen-band2-image27-2.adoc[1812 Marie Philippine Krückeberg Marriage]
** xref:petzen:petzen-band2-image339.adoc[1816 Christine Louise Krückeberg Marriage]

== For Their Descendents and Them

We need on-site Bückeburg archives research done.

Put togehter the further reaseach needed. Be sure I have a complete list of individuals.:
Determine the recorded events needed--marriage, confirmation, baptism--and its Nachträge
for these individuals: 

* Bleeke brothers and their wives and children:
** xref:research:bueckeburg-bleeke-research.adoc[]
** xref:research:petzen-frille-research.adoc[]
* Philippine Eleonore nee Werkmeister Krückeberg.
* Weilands who settled in Adams CO, and the wives and children
* Johann Heinrich Krückeberg, his wife and children
** Anyone else in the family tree who would be found in the latest volume.:


== Krückeberg Pedigree Analysis

The most recent Nachtrag that appears for a Krückeberg in "Verzeichnis der Getauften, Konfirmierten,
Getrauten und Gestorbenen 1785-1827" is December 1, 1816, the xref:petzen:petzen-band2-image339.adoc[marriage
record for Christine Louise Krückeberg].

At some point, Christine Louise Krückeberg's December 1, 1816, marriage record was supplemented with
her birth and death dates. The marriage record states her father, Johann Heinrich Krückeberg,
is deceased, and that he had lived at *no. 19 Evesen*. The bride, his daughter, also lived
in Evesen prior to the marriage. No number is given for her.

As the Nachtrag says, Christine Louise's birth was xref:petzen:petzen-band2-image71.adoc[recorded on April 26,
1798]. Furthermore, the Nachtrag in her birth record gives the correct future marriage date of December
1, 1816. The Nachträge are confirmed as accurate.

Her birth-and-baptism record also gives her family's residence as "no. 19 Evesen". From the
birth record we have these family group details:

.Johann Heinrich Krückeberg Family Group
|===
|||Birthdate

|*Father*|Johann Heinrich Krückeberg|

|*Mother*|Kathar. Sophie Krömer|

|*Daughter*|Christine Louise|April 26, 1798

|*Residence* 2+|No. 19 Evesen
|===

Her xref:petzen:petzen-band2-image207-2.[confirmation record] is found at the expected date of April 7, 1811,
when she was three and a half weeks shy of 13 years old. Her identity is confirmed by matching the information 
given for her parent's names, her birthdate and the families current residence with the same information
in her marriage record.

.Facts from April 7, 1811 Confirmation of Christine Louise Krückeberg
|===
|||Confirmation Date|Birthdate

|*Father*|Johann Heinrich Krückeberg||

|*Mother*|Kathar. Sophie Krömer||

|*Daughter*|Christine Louise|April 7, 1811|April 26, 1798

|*Parent's Current Residence* 3+|No. 19 Evesen
|===

Only one of her mother's given name's differs.

