= TODO

== For the Pedigree of Carl Friedrich Krückeberg (born 1807) and Johann Heinrich Krückeberg

* Write up a explanation and the significance of the Nachträge.

* These are the most recent Nachträge:
** xref:petzen:petzen-band2-image125-entry31.adoc[1812 Carloline Dorothee Krückeberg Baptism]
** xref:petzen:petzen-band2-image27.adoc[1812 Philippine Caroline Christine Krückeberg Marriage]
** xref:petzen:petzen-band2-image27-2.adoc[1812 Marie Philippine Krückeberg Marriage]
** xref:petzen:petzen-band2-image339.adoc[1816 Christine Louise Krückeberg Marriage]

== For Their Descendents and Them

We need on-site Bückeburg archives research done.

Put togehter the further reaseach needed. Be sure I have a complete list of individuals.:
Determine the recorded events needed--marriage, confirmation, baptism--and its Nachträge
for these individuals: 

* Bleeke brothers and their wives and children:
** xref:research:bueckeburg-bleeke-research.adoc[]
** xref:research:petzen-frille-research.adoc[]
* Philippine Eleonore nee Werkmeister Krückeberg.
* Weilands who settled in Adams CO, and the wives and children
* Johann Heinrich Krückeberg, his wife and children
** Anyone else in the family tree who would be found in the latest volume.:


== Krückeberg Pedigree Analysis

=== Johann Heinrich Family Group, No. 19 Evesen

==== Nachtrage Trail

The most recent Nachtrag that appears for a Krückeberg in "Verzeichnis der Getauften, Konfirmierten,
Getrauten und Gestorbenen 1785-1827" is the December 1, 1816, the xref:petzen:petzen-band2-image339.adoc[marriage
record for Christine Louise Krückeberg].

[caption="Johann Heinrich Krückeberg Family Group on December 1, 1816: "]
.upon marriage of daughter Christine Louise 
|===
|||Marriage Date|

|*Father*|Johann Heinrich Krückeberg, deceased|

|*Mother*| Sophie Krömer|

|*Daughter*|Christine Louise|April 26, 1798

|*Residence* 2+|No. 19 Evesen
|===



At some point, Christine Louise Krückeberg's December 1, 1816, marriage record was supplemented with
her birth and death dates. The marriage record states her father, Johann Heinrich Krückeberg,
is deceased, and that he had lived at *no. 19 Evesen*. The bride, his daughter, also lived
in Evesen prior to the marriage. No number is given for her.

As the Nachtrag states, Christine Louise's birth occurred xref:petzen:petzen-band2-image71.adoc[on April 26,
1798]. Her her birth record was later supplemented with the correct future marriage date December
1, 1816. The Nachträge are consistent with each other.

Her birth-and-baptism record also gives her family's residence as "no. 19 Evesen". From the
birth record we have these family group details:

[caption="Johann Heinrich Krückeberg Family Group on April 26, 1798: "]
.upon birth of daughter Christine Louise 
|===
|||Birthdate

|*Father*|Johann Heinrich Krückeberg |

|*Mother*|Kathar. Sophie Krömer|

|*Daughter*|Christine Louise|April 26, 1798

|*Residence* 2+|No. 19 Evesen
|===

Her xref:petzen:petzen-band2-image207-2.adoc[confirmation record] is found at the expected date of April 7, 1811,
when she was three and a half weeks shy of 13 years old. Her identity is confirmed by matching the information 
given for her parent's names, her birthdate and the families current residence with the same information
in her marriage record.

.Facts from April 7, 1811 Confirmation of Christine Louise Krückeberg
|===
|||Confirmation Date|Birthdate

|*Father*|Johann Heinrich Krückeberg||

|*Mother*|Anne Sophie Krömer||

|*Daughter*|Christine Louise|April 7, 1811|April 26, 1798

|*Parent's Current Residence* 3+|No. 19 Evesen
|===

Her mother's given name's differ slightly between these two records: "Anne Sophie Kromer" vs "Kathar[ine] Sophie Krömer".
The xref:petzen:petzen-band2-image5-1.adoc[marriage record] resolves this discrepancy....todo: explain

Other children are given in these records:
* xref:petzen:petzen-band2-image59-60.adoc[1793 Philippina Eleonora Kruckebergen Baptism]
* xref:petzen:petzen-band2-image71.adoc[1798 Christine Louise Krückeberg Baptism]
* xref:petzen:petzen-band2-image82-1.adoc[1803 Sophie Caroline Krückeberg Birth]

Prospective child, though mother's given  name is "off".
* xref:petzen:petzen-band2-image52.adoc[1791 Friderich Wilhelm Krückeberg Baptism]
