output_folder: /home/kurt/adocs-4-genealogy/m/timelines/pages
input_folder: /home/kurt/adocs-4-genealogy
timelines:
  - output_file: sophia-maria-k-1741.adoc
    page_header: |
      = Sophia Maria Krückeberg [1741-1801]
      :page-role: doc-width
    module: petzen
    input_files:
      - petzen-band1a-image163.adoc
      - petzen-band1a-image310-left.adoc
      - petzen-band2-image239.adoc
  - output_file: johann-heinrich-k-1744.adoc
    page_header: |
      = Johann Heinrich Krückeberg [1744-1822]
      :page-role: doc-width
    module: petzen
    input_files:
      - petzen-band1a-image167.adoc
      - petzen-band2-image27-2-birth.adoc
  - output_file: carl-philip-k-1750.adoc
    page_header: |
      = Carl Philip Heinrich Krückeberg [1750-?]
      :page-role: doc-width
    module: petzen
    input_files:
      - petzen-band1a-image180.adoc
      - petzen-band1a-image313.adoc
  - output_file: jobst-heinrich-1767-timeline.adoc
    page_header: |
      = Jobst Heinrich Krückeberg [1765-1822]
      :page-role: doc-width
    module: petzen
    input_files:
      - petzen-band1a-image211.adoc
      - petzen-band1a-image319.adoc
      - petzen-band2-image5-3.adoc
      - petzen-band2-image55.adoc
      - petzen-band2-image70.adoc
      - petzen-band2-image239.adoc
      - petzen-band2-image81.adoc
      - petzen-band2-image198.adoc
      - petzen-band2-image91.adoc
      - petzen-band2-image96.adoc
      - petzen-band2-image207-1.adoc
      - petzen-band2-image27.adoc
      - petzen-band2-image314.adoc
  - output_file: johann-heinrich-k-1767.adoc
    page_header: |
      = Johann Heinrich Krückeberg [1767-1805]
      :page-role: doc-width
    module: petzen
    input_files:
      - petzen-band1a-image220.adoc
      - petzen-band1a-image320.adoc
      - petzen-band2-image5-1.adoc
      - petzen-band2-image52.adoc
      - petzen-band2-image59-60.adoc
      - petzen-band2-image230.adoc
      - petzen-band2-image71.adoc
      - petzen-band2-image82-1.adoc
      - petzen-band2-image243.adoc
      - petzen-band2-image201.adoc
      - petzen-band2-image207-2.adoc
      - petzen-band2-image339.adoc
      - petzen-band2-image211-3.adoc
