= Conrad Buuck's Uncertain Date of Birth

The xref:families:buuck.adoc[Declaration of Intention to Naturalize] of **Ernst Diedrich Buuck** (1805-1874) states
that he immigrated in 1841 and that two of his sons (who as members of his family) were on the voyage were **Ernst Book**
and **Conrad Book**.

Alas, my dear genealogist friends, something is amiss! Which **Conrad Book** is this and when was he actually born?

Consider:

* Every Ancestry.com tree with has noteworthy numbers of the Buucks who immigrated to Preble township
has the birthdate of **Ernst Diedrich Conrad Buuck (1841-1908)**, the son of **Ernst Diedrich Buuck(1805-1974)**
as: 20 July 1841.
* However, according to the transcription above **Conrad Book** was around three months old when the
family immigrated.

Could it be that:

* The Ancestry trees are correct and somehow something was "lost in translation" when Ernst Diedrich (1805-1874)
made his Declaration to naturilize.
* The Ancestry tree are wrong and the Declaration is right: **Conrad Book** was born before the family
departed in April of 1841.
* Something else is amiss.

Obviously, link:https:/www.ancestry.com[Ancestry.com] family trees are not umimpeachable sources of reliable information,
and the only way to reliably discover the truth will be to eventually examine the Windheim church registers (ugh!)
and any biogrpahical information about this family in the Friedheim church records.

