= Finding Original Familienschein

In answer to my question:

[quote, My question about Familenschein]
____
I have this typewritten German document that has written at the top "Familienschein des Auswanderers Carl Krueckeberg von Nr. 18 in Berenbusch, Deutschland". It describes his and his wife's birth and baptism, the date of their marriage and the details of the births, baptisms and confirmations of their children. It ends with: 
Die Übereinstimmung vorstehender Angaben mit dem hiesigen Kirchenbüchern bescheinigt den Audswandern unter Anwünschung des göttlichen Segens."

I believe this was typewritten by my late father's uncle many years ago.

Questions:

1. What this document something that was required to emigrate, and
2. would the original document still exist in the civil records today. Berenbusch was in Schaumburg-Lippe, northeast of Bückeburg, just north of Evesen.
____

According the Andrea Brenntschneider:

[quote, answer from Andrea]
____
To answer your questions: 1, it was not required to have such a document to emigrate. 2, I am not sure if the priest actually made a copy of the document or if this is the only version for the personal use of the family.
If a copy was made, I would check at the parish office or church archive.
____
