= Finding Original Familienschein

TODO: Please provide a link to Familienschein in the email.

== Brief zu Bückeburg Abteilung des Niedersächishes Landesarchivs

Sehr geehrte Damen und Herren,

ich forsche zur Geschichte meiner Vorfahren väterlicherseits, die im Jahr 1850 aus dem Dorf Berenbusch (Parochie Petzen, Schaumburg-Lippe) nach Indiana, USA ausgewandert sind.

Ich besitze eine maschinenschriftliche Abschrift eines Dokuments mit dem Titel:  
**„Familienschein des Auswanderers Carl Krueckeberg von Nr. 18 in Berenbusch, Deutschland“**  
Das Dokument enthält Angaben zu Geburt, Taufe, Konfirmation und Heirat von Carl Krückeberg, seiner Ehefrau und deren Kindern. Es endet mit der Formel:  
**„Die Übereinstimmung vorstehender Angaben mit dem hiesigen Kirchenbüchern bescheinigt den Auswandern unter Anwünschung des göttlichen Segens.“**

Ich vermute, dass dieses Dokument um 1850 vom Pfarrer der evangelisch-lutherischen Kirchengemeinde Petzen auf Grundlage der dortigen Kirchenbücher erstellt wurde.

Daher meine Frage:  
**Ist es möglich, dass eine Abschrift oder ein Durchschlag dieses Familienscheins, oder ein entsprechender Eintrag in einem Registraturbuch oder einer Akte, in Ihrem Archiv erhalten ist?**  
Gibt es eventuell ergänzende Verwaltungsunterlagen der Kirchengemeinde Petzen, in denen die Ausstellung solcher Familienscheine dokumentiert wurde?

Ich bin für jede Hilfe oder Hinweise sehr dankbar.

Mit freundlichen Grüßen  
[Ihr Vorname Nachname]  
[Ort, ggf. Land]  
[E-Mail-Adresse]



== Brief zu Pfarrers des Petzen Gemeide:

Evangelisch-Lutherische Kirchengemeinde Meinsen-Petzen  
z. Hd. des Pfarrers / der Pfarrerin  
[Adresse ergänzen, falls bekannt]

[Ihr Ort], [Datum]

Sehr geehrter Herr Pastor / Sehr geehrte Frau Pastorin,

ich schreibe Ihnen im Rahmen meiner Ahnenforschung zur Familie meines Ururgroßvaters Carl Krückeberg, der im Jahr 1850 mit seiner Familie aus Berenbusch (damals zur Kirchengemeinde Petzen gehörend) in die Vereinigten Staaten ausgewandert ist.

Ein erhaltenes Dokument trägt den Titel:  
**„Familienschein des Auswanderers Carl Krueckeberg von Nr. 18 in Berenbusch“**  
und wurde offenbar auf Grundlage der Kirchenbücher der Gemeinde Petzen erstellt.

Ich möchte höflich anfragen:  
- Sind bei Ihnen oder in älteren Gemeindearchiven eventuell noch Unterlagen vorhanden, die mit der Ausstellung von Familienscheinen in Verbindung stehen?  
- Gibt es eventuell alte Pfarrakten oder Auswanderungsdokumente, in denen solche Vorgänge verzeichnet wurden?

Für jeden Hinweis oder eine Weiterleitung meiner Anfrage an zuständige Stellen wäre ich Ihnen sehr dankbar.

Mit freundlichen Grüßen  
[Ihr Vorname Nachname]  
[Adresse oder E-Mail, falls gewünscht]

