= Weiland Drinkhuth Questions

== The Questions

Steve asked Reiner Eberhardt these xref:attachment$friedrich-wilhelm-weiland-evesen-no-20-fragen.pdf[questions].

== The Reply

He replied:

....
Hello Steve, I am only registered with Archion in the winter and therefore
cannot currently verify the birth entries of the children of Friedrich Wilhelm
Weiland.
 
Regarding the three possible wives who have the IDs G1NJ-ZSB, MJ6C-12Z, and
GZWC-WH4 on FamilySearch, I would exclude the last two Drinkuth Oberhahne.
According to your research, it is stated for the second daughter and the second
son that their mother comes from Wülpke No. 1.  Possible mothers would be
G1NJ-ZSB or G1NV-DS2.  One would need to look for the death entry in the church
book of Petzen to more precisely determine the correct wife.  Based on the
birth records of the children, I believe that it is the same mother or that
there is only one wife. The designation Döpking von Wülpke No. 1 probably
refers to the same person.  Regarding the 3rd question, I can say that there
are indeed church records from Petzen even after 1827. From 1827 until around
1875, one can view microfiche in the state archive in Bückeburg.
 
Greetings Reiner
....
