= Petzen and Frille Bückeburg Archive Research

These details and any Nachträge

== Locations

=== Berenbusch

https://www.arcinsys.niedersachsen.de/arcinsys/detailAction?detailid=v4979525[Die Stätte Nr. 14 zu Berenbusch]

== Individuals

I would like to have birth/baptism, confirmation, and marriage data for the following two 
Bleeke brothers, who were members of the Frille congregation:

=== Bleeke

I would to confirm the *marriage dates* for these two Bleekes:

|===
|Groom|Bride|Marriage Date|Church

|Carl Fridrich Bleeke
|Marie Luise Niemann 
|March 12, 1820,
|Frille.

|Johann Heinrich Philipp Bleeke
|Christine Maria Schwier
|Spring of 1819
|Frille

|Christian Friedrich Bleeke
|Christine Luise Eloenore Krückeberg
|Nov 26, 1826
|Frille
|===

I would like to confirm these details about Carl Friedrich Bleeke's children:

|===
|Child|Aprox. Birth

|Christine Blecke/Bleeke| around 1820

|Carl Friedrich Bleeke| October 1823

|Marie Christine Bleeke| January 5, 1826

|Christian Friederich Bleeke| February 1828

|Johann Hartweg Bleeke| October 11, 1830

|Gottlieb Bleeke| 1831

|Sophie Luise Bleeke| March 3, 1833

|Eleonore (Ellen) Bleeke| February 20, 1835

|Christine Louise Bleeke| March 31
|===

I would like to confirm these details for the children of Johann Heinrich Philipp Bleeke:

|===
|Name|Birth|Baptism|Confirmation|Confirmed|Death

| Carl Heinrich| April 27|on April 30, 1818| Sunday after Easter 1832|skip

| Christian Fridrich| May 7|on May 13, 1821.|Judica Sunday 1835|skip

| Carl Friedrich| July 17|on July 20, 1823. |?|May 11, 1825

| Carl Friedrich Wilhelm| November 30| December 4, 1825|skip|skip

| Christine Maria| August 11| August 17, 1828|skip|skip

| Christine Sophie Eleonore|August 13, 1831|August 21, 1831|skip|skip

| Marie Louise Eleonore| November 15, 1833|November 24, 1833|skip|skip
|===

=== Krückeberg:

The post-1827 Kirchenbuch should be search from 1828 to 185?? for any Krückebergs mentioned.
The surname will be underlined.

It should be search also for these specific records:

I would like these marriage facts for these two Krückebergs confirmed:
. Johann Heinrich Krückeberg married Caroline Sophie Weÿland on January 26, 1833.
. Carl Friedrich Krückeberg married Luise Dorothea Weiland on November 16, 1834.

I would like these facts for the children of Johann Heinrich Krückeberg (born 1806) confirmed:

[arabic,start=1]
. Caroline Philippine Dorathee, born on February 27, 1834, and baptized on March 9 of the same year. +
Her Godparents were: Doratha Weÿland, Philippine Watermann, and Caroline Krückeberg.
. Christine Sophie Eleonore, born on August 22 and baptized on the 28th of the same month 1835. +
Her godmother is: Christine Bleeke.
. Philippine Christine, born on June 18, 1837, and baptized on the 24th of the same month. +
Her godmother is: Caroline Most.

I would like these facts for the children of Carl Friedrich Krückeberg (born 1807) confirmed:

. Carl Heinrich Wilhelm Krückeberg, born Feb. 4, 1835  

I would like these death records confirmed:

[arabic,start=1]
. Philippine Eleonore geb. Werkmeister Krückeberg, die am 5.4.83 geboren
wurde, confirmiert am ???, gestorben am ?.?.38 
. Philippine Christine Eleonore nee Tegtmeyer Krückeberg, who married on
xref:petzen:petzen-band2-image5-3.adoc[Oct 12, 1790], and died on xref:petzen:petzen-band2-image314[8. ??? 1849].
