= Petzen and Frille Bückeburg Archive Research

These details and any Nachträge

== Locations

=== Berenbusch

https://www.arcinsys.niedersachsen.de/arcinsys/detailAction?detailid=v4979525[Die Stätte Nr. 14 zu Berenbusch]

== Individuals

I would like to have birth/baptism, confirmation, and marriage data for the following two 
Bleeke brothers, who were members of the Frille congregation:

=== Bleeke

TODO: Add Christian Bleeke to this list and his children

I would to confirm the *marriage dates* for these two Bleekes:

. Carl Fridrich Bleeke, born on October 30, 1794, and baptized in the church of Frille. +
He was married to Marie Luise Niemann on March 12, 1820, in Frille.
. Johann Heinrich Philipp Bleeke, who was born on November 3, 1797. +
He was married in the spring of 1819 to Christine Maria Schwier, a daughter of Christian
Fridrich Schwier and Catharina Margaretha, née Rösner.

I would like to confirm these details about Carl Friedrich Bleeke's children:

[arabic,start=1]
. Christine Blecke/Bleeke, born around 1820
. Carl Friedrich Bleeke, born October 1823
. Marie Christine Bleeke, born January 5, 1826
. Christian Friederich Bleeke, born February 1828
. Johann Hartweg Bleeke, born October 11, 1830
. Gottlieb Bleeke, born 1831
. Sophie Luise Bleeke, born March 3, 1833
. Eleonore (Ellen) Bleeke, born February 20, 1835
. Christine Louise Bleeke, March 31

I would like to confirm these details for the children of Johann Heinrich Philipp Bleeke:

[arabic,start=1]
. Carl Heinrich, born on April 27 and baptized on April 30, 1818. +
Godfather: Fridrich Schwier, confirmed on Sunday after Easter 1832; died
on March 25, 1839
. Christian Fridrich, born on May 7 and baptized on May 13, 1821. +
Godparents: Carl Fridrich Bleeke, confirmed on Judica Sunday 1835.
. Carl Friedrich, born on July 17 and baptized on July 20, 1823. +
Godfather: Christian Friedrich Bleeke; died on May 11, 1825.
. Carl Friedrich Wilhelm, born on November 30 and baptized on December 4, 1825. +
Godparents: Friedrich Meier and Christ. Bleeke
. Christine Maria, born on August 11 and baptized on August 17, 1828. +
Godparents: Anna Soph. Schwier and Maria Meier.
. Christine Sophie Eleonore, born on August 13 and baptized on August 21, 1831. +
Godparents: Christine Bleeke
. Marie Louise Eleonore, born on November 15 and baptized on November 24, 1833. +
Godparents: Louise Schwier and Marie Bleeke

=== Krückeberg:

The post-1827 Kirchenbuch should be search from 1828 to 185?? for any Krückebergs mentioned.

It should be search also for these specific records:

TODO : mention Auswanderung record.

I would like these marriage facts for these two Krückebergs confirmed:
. Johann Heinrich Krückeberg ....married
. Carl Friedrich Krückeberg.... married

I would like these facts for the children of Johann Heinrich Krückeberg (born 1806) confirmed:

[arabic,start=1]
. Caroline Philippine Dorathee, born on February 27, 1834, and baptized on March 9 of the same year. +
Her Godparents were: Doratha Weÿland, Philippine Watermann, and Caroline Krückeberg.
. Christine Sophie Eleonore, born on August 22 and baptized on the 28th of the same month 1835. +
Her godmother is: Christine Bleeke.
. Philippine Christine, born on June 18, 1837, and baptized on the 24th of the same month. +
Her godmother is: Caroline Most.

I would like these facts for the children of Carl Friedrich Krückeberg (born 1807) confirmed:

. TODO 

I would like these death records confirmed:

[arabic,start=1]
. Philippine Eleonore geb. Werkmeister Krückeberg, die am 5.4.83 geboren
wurde, confirmiert am ???, gestorben am ?.?.38 
. Philippine Christine Eleonore nee Tegtmeyer Krückeberg, who married on
xref:petzen:petzen-band2-image5-3.adoc[Oct 12, 1790], and died on xref:petzen:petzen-band2-image314[8. ??? 1849].
