= Petzen and Frille Bückeburg Archive Research

These details and any Nachträge

Krückeberg Familie:
Get details from Familienschen:

[arabic,start=1]
.
.



Ich hätte gerne Geburts-/Tauf-, Konfirmations- und Heiratsdaten für die folgenden zwei
Bleeke-Brüder, die Mitglieder der Gemeinde Frille waren:

Bleeke

1. Carl Fridrich Bleeke, geboren am 30. Oktober 1794 und getauft
in der Kirche von Frille. Er wurde am 12. März 1820 in Frille
mit Marie Luise Niemann verheiratet.

2. Johann Heinrich Philipp Bleeke, der am 3. November 1797 geboren wurde. Er war
im Frühjahr 1819 mit Christine Maria Schwier verheiratet, einer Tochter von Christian
Fridrich Schwier und Catharina Margaretha geboren Rösner.

Ich habe ihr Geburts- und Taufregister auf Archion gefunden. Ich möchte
bitten, die Angaben zur Heirat zu bestätigen. Ich möchte auch die 
Geburt/Taufdaten ihrer Kinder bestätigen.

Hier sind Details über die Kinder von Carl Friedrich Bleeke, die ich
gerne bestätigt haben möchte:

1. Christine Blecke, Geburt ungefähr 1820
2. Carl Friedrich Bleeke, Geburt Oktober 1823
3. Marie Christine Bleeke, Geburt 5. Januar 1826
4. Christian Friederich Bleeke, Geburt Feb 1828
5. Johann Hartweg Bleeke, Geburt 11. Oktober 1830
6. Gottlieb Bleeke, Geburt 1831
7. Sophie Luise Bleeke, Geburt 3 März 1833
8. Eleonore (Ellen) Bleeke, Geburt 20. Februar 1835
9. Christine Louise Bleeke, 31. März

Hier sind Details über die Kinder von Johann Heinrich Philipp Bleeke, die ich
gerne bestätigt haben möchte:

1. Carl Heinrich, geboren den 27. April u. getauft den 30. April 1818.
Taufpate: Fridrich Schwier, konfirmiert am Sonnt. n. Ostern 1832; gest.
den 25 März 1839
2. Christian Fridrich, geboren den 7 Mai und getauft den 13 Mai 1821.
Taufpaten: Carl Fridrich Bleeke, konfirmiert am Sonnt. Judica 1835.
3. Carl Fridrich, geboren den 17 Juli u. getauft den 20 Juli 1823.
Taufpathe: Christian Fridrich Bleeke; gestorben den 11 Mai 1825.
4. Carl Fridrich Wilhelm, geboren den 30 November u. getauft den 4
Dezember 1825. Taufpaten: Fridrich Meier und Christ. Bleeke
5. Christine Maria, geboren den 11 u. getauft den 17 August 1828.
Pathen: Anna Soph. Schwier und Maria Meier.
6. Christine Sophie Eleonore, geboren den 13 August u. getauft den 21
August 1831. Pathen: Christine Bleeke
7. Marie Louise Eleonore, geboren den 15 und getauft den 24 November 1833.
Pathen: Louise Schwier und Marie Bleeke

Auch...

Ich hätte gerne Leib.... für:
[arabic,start=1]
. Philippine Eleonore geb. Werkmeister Krückeberg, die am 5.4.83 geboren
wurde, confirmiert am ???, gestorben am ?.?.38 
. Philippine Christine Eleonore geb. Tegtmeyer Krückeberg, verheiratet am
xref:petzen-band2-image5-3.adoc[Oct 12, 1790], starb xref:petzen-band2-image314[8. ??? 1849].
