= What was Philippine Eleonore's Maiden Name?

On xref:petzen-band2-image125-entry31[Dec. 2 1812], when Caroline Dorothee Krückeberg, the daughter of Carl Friedrich
Gottlieb Krückeberg and Philippine Eleonore, was baptized, her mother's name
is recorded as:  **"Philippine Leonore geb. Blecken aus N. 11 in Evesen"**. There is
also an addenda attached to her written in a smaller hand: "get. 4.5.85". "get" or getauft (baptized)
on May 4, 1785.

Compare this information with that found in the xref:etzen/petzen-band2-image12-3[March 13,
1803, marriage record] for Carl Friedrich Gottlieb Krückeberg, where the name of his Braut (bride) is:
**"Jgfr Philippine Eleonore Werkmeister"**, whose Ort and number are: **Evesen 11**.

Looking at the xref:petzen-band1a-image287[baptism recorded on May 4, 1785], it is
for: **Philippina Eleonore Wekmeister**, whose father is "Tönnies (diminutive for Anton) **Werkmeister** aus
**Evesen no. 11**".

Since "Philippine Eleonore Werkmeister" was only 19 when she married, she had not previously been married.

Why would her mother's maiden name be given as "Blecke" when her daughter
Caroline Dorothee was born?  And why would the May 24, 1807, birth record of her
brother, Carl Friedrich Krückeberg, also have this same discrepancy, listing
his mother as: **"Philippine Lenore gen. Blecken aus n. 11 in Evesen"**?

Why would the pastor or sexton "confuse" the maiden name? Why would he be "confused"
both in 1807 and then again in 1812, making the same "mistake"? There church records
were legally mandated documents. This was a small parish in Schaumburg-Lippe,
an agrarian, rural society!

More than one family might reside at an address. In 1821, for example, Johann
Heinrich Krückeberg dies. He resides at No. 10 Berenbusch. In 1822, Jobst
Heinrich dies. He lives at No. 10 Berenbusch.



