= Krückeberg and Bleekes in 19^th^ Century Indiana School Enumerations

See the **School Enumerataions** section in this Indiana State Library,
Genealogy Division, article on
xref:attachment$school-enumeration-Union-township-indiana-20-September-1853.pdf[Indiana
State Censuses and Alternate Enumerations]. While the article does not properly
show that Adams County, Indiana, did maintain a school enumeration, the
existence of the an Adams County school enumerations was mentioned in an
article in the Indiana Genealogist, Vol.  13, Issue 3 (Oct 2002).

The head of household of those in Union township, Adams County, Indiana--the
Bleekes, Krückebergs, and others--who had children in school were noted in an
Indiana School Enumeration along with their child's name. 

This the original Indiana Genealogist article
xref:attachment$Indiana_Genealogist_Sept_2002_School_enumerations_1853_of_Union_township_Adams_county_Indiana.pdf[School
Days, School Days] that excerpts the school enumeration for Adams County, and
which explains that "school record files" are held at the Indiana State
Archives and "researchers may obtain the complete list (of those in Adams
County) from the AArchives staff." The article's call number in the Genealogy
Center is below:

[cols="4,1,4"]
|===
|Periodical|Year|Publisher

|**Indiana Genealogist** +
Vol. 13, Issue 3 (Oct 2002) +
ACPL Call #: 977.2 IN2015|2002|**Indiana Genealogical Society** +
POB 10507 +
Fort Wayne, IN 46852
|===

