= Krückeberg and Bleekes in 19^th^ Century Indiana School Enumerations

See the **School Enumerataions** section in this Indiana State Library, Genealogy Division, article on
xref:attachment$school-enumeration-Union-township-indiana-20-September-1853.pdf[Indiana State Censuses
and Alternate Enumerations].

The head of household of those in Union township, Adams County, Indiana--the Bleekes, Krückebergs, and
others--who had children in school were noted in an Indiana School Enumeration along with their child's name. 

The existence of the Indiana school enumerations was mentioned in an article in the Indiana Genealogist, Vol. 13, Issue 3 (Oct 2002).

This the original Indiana State xref:attachment$Indiana_Genealogist_Sept_2002_School_enumerations_1853_of_Union_township_Adams_county_Indiana.pdf[School Days,
School Days].

This periodical's call #er in the Genealogy Center is:

[cols="4,1,4"]
|===
|Periodical|Year|Publisher

|**Indiana Genealogist** +
Vol. 13, Issue 3 (Oct 2002) +
ACPL Call #: 977.2 IN2015|2002|**Indiana Genealogical Society** +
POB 10507 +
Fort Wayne, IN 46852
|===

