= Todds Research Report

Below is Todd's report, of 6 July 2024, on his Krueckeberg research done in Adams county, Indiana:

[quote, Todd's report of his research finds]
____
I went to the court house and the Annex (old Jr High) that holds the Auditors and Recorders office.  This office holds all
the dead's for lands in Adams County.

[arabic]
.  The Adams County recorder, Mrs. Krueckeberg, will take a written request for court settlements.  I requested **Ernst H
Krueckeberg's**, his wife **Louisa's** and **my grandfather's** courts records. You cannot photograph them. It costs $ 1.00
per page for copies. This request could be made for **Carl H W Krueckeberg** as well.

.  Looking for Ernst H Naturalization record.  Carl H W is “Charles” can be found at the Decatur library as Mel has
reported.  A **Buuck family book** talks about **Order book A** in the Adams county court house.  I did not it at
the Adams county library.

. I did find the land patient for **Charles (father)** with the Indiana Governor's signature.  1850 land of the 34.6 acres
from Swamp Act from the Federal land office.  I have a copy of the Arron Carpenter signed by the president.  Want to see
if we can get this from National Archives (Kurt need your help).  The FT Wayne library told me that was only given to the
land owner. Maybe Sharon Tester still has it?

.  **Dorris nee Krueckeberg Martin** has 100 or so pictures that show **Ernst H** with his children and grandchildren.  
HELP:  Need recommendation on how to scan and log for all future generation.  Dorris does not drive any more but lives by
herself in Town House in Ft Wayne.  Maybe Familysearch.org and tag all the people?

. **Emmanuel Lutheran** will have 175 year celebration this fall.  I will try to get details to pass along.  Still not sure
why **Ernst** does not have a profile in German at the Church.  They continued in German till 1947?  Mel help me with that
date.

. Many pictures of Bleeke side of the family.  A picture of **Christina Schwer** the wife of **John H Bleeke**.  Mostly of
Gretchens mother as my Dad called her grandma Bleeke.  She made a small blanket for me.

. The Buuck book refers to Ft Wayne German newspaper called “Dietrich” printed in Ft Wayne in German.  This takes it to a
whole new level.  I do not speak German. I think are on film at Genealogy Center downtown Allen Co Library.  Not sure how
long it was printed.

I did meet with Norma the wife of Tim and in-laws to **Edgar Krueckeberg**.  I did shake the hand of Sharon Tester, daughter
of Alvin Krueckeberg.

Please let me know if you have any thoughts or ideas on the pictures.  I think a few are from your branch.  I am looking for
as many original pictures as possible.  Mel has agreed to scan what he has from the trip back the home land and original
church.
____

