= Bleeke, page 34

____
7. Simmermann & Dzierzanowsky: zwischen Elmg Hlam,
8. Bleecke & Meerhoff: zwischen Plum & Western-Row,
9. Wellmann & Bultmann: zwischen Western Kow & John-Street,
10. L. Wehmer & Knost: östlich von Broadwag
11. Bolte & Steinkamp: an der Nordseite der Corporation -Line.
Am nächsten Sonntage soll es in der Kirche bekannt gewe-
werden, daß wir am folgenden Tage, dem Montage, anfangen zu collektiren.
Vorgelesen u. genehmigt.
Wehmer
di cox geggenn
Versamml. des K. R. der Vorddeusch. Luth. Gem. zu Cincierati
" den 27. May 1839.
Die Collekte soll am nächsten Montage ihren Anfang nehmen, was am Sonntage
bekannt zu machen ist.
Burchelt & L.Wehmer sollen bei den Bänken nachfragen, ob wir Geld
auf ziemlich lange Zeit getrefen leihen können.
Wir wollen bei unserm Tischlerschop wachen; nämlich am Dienst-Burchelt,
am Mitto. Steinkamp, am Donnerst. Meyer, am freit. Simmermann
am Sonnab. Blecokez am Sonnt. Havekotte, am Mont. Wiemann
am Dienst. Niemann, am Mittw. Wemax, am Donnerst. Wehmer, am
freit. v. Segzern.
das untere Gebälte muß so geschwind als möglich gemacht worden.
Havekotte soll berechtigt sein 1 od. 2. Mann anzustellen um die
überflüssige Erde hinauswerfen zu lassen.
Vorgelesen u genehmigt.
I von Seggern
x
Wehmer
Versamml. des R. R. der NorddeutchRuth-Gemeinde
Cincinnati
am 6. Juni 1839.
In Abwwesenhelt des Peste Metertärt Wehmer wurde der Pastor Mollmann
zum Sekretär ernannt.
der Schatzmeister brachte seine Rechnung ein für das verflossene
Monat.
Einnahme N 385, 72-
Ausgabe.
916, 15.
____
