= Bleeke, page 28

____
Lomm. ist Wellmann u. D. Meyer.

beschlossen, daß der Kirchenrath sich erkündige, ob Cart Liemann das
Anstreichen der Holzarbeit, so billig [thun] will, wie möglich, deßhalb
hat der Kirchenrath nächsten Sonntag Nachm[ittag]. 2 Uhr sich zu versammeln
und die Erfolge der Erkundigungen einzubringen.

Vorgelesen und genehmigt.

Wehmer

Ir von Seggern

Versammlung des R. R. der Norddeutsche Geweinde in

lincinnati, den 3. März 1839.

Beschl[ossen]. 1, daß eine Comm. von 2 Mann ernannt werde um Holz zu unsrea

Kirchengebäude zu käufen. Ernannt sind Wehmer u. Timmermann.

2, daß eine Comm. erwählt werde, un die Orte auszumachen, wo wir

die Nägel zu unserm Gebäude am billigsten bekommen können, oder

zu sehen, ob wir nicht Nägel zum Geschenk erhalten

können.

Vorgelesen u. genehmigt

Wehmer

r von Seggern

Versammlung des R. R. vom 7. März.

Nach Eröffnung der Versammlung wurde beschlossen, daß der Kirchenrath

in verschiedene Committen eingetheilt werde.

1. Zur Tischler-Committe wurden ernannt L. Wehmer, Havekothe & D. Simmermann.

2. Comm. zur Aufsicht der Steinmaurer: Fr. v. Seggern & Bleecke.

3. Comm. zur Aufsicht über die Brickarbeiter: A. Burchelt, Wellmann & Wiemann

H. Vajen brachte eine Rechnung ein, die angenommen wurde, von § 1, 2212.

P. Wehmer brachte eine Rechnung ein, die angenommen wurde, betrug J 9, 12 12.

W. Burchelt brachte eine Rechung, die angenommen wurde, betrug D. 13, 73.

J. H. Wellmann brachte eine Rechnung von §. 3,42, welche angenommen wurde.

John de Bur brachte seine Rechnung für Ausgraben des Kellers

betrug § 156, 75., welche angenommen wurde.

Der Schatzmeister brachte die monatliche Rechnung, Bestand wie folgt:

Einnahme 8821,86 12.

Ausgabe B. 163. 25.

blieb in Casse. § 658, 6112.

welche angenommen wurde.

Beschlossen die Bekanntwachung einer Collecte für eine arme Witwe aus unhrer

Gemeinde, für den de nächstfolgenden Soontag-
____
