= What Documents are Where
                
The foreward to _An index to naturalization records in pre-1907 order books of Indiana county courts_
explains there is a  difference between naturalization documents and the notes made by court clerks
in court order books about naturalization proceedings:

[quote, Foreword to An Index to Naturalization Record in pre-1907 Order Books of Indiana County Courts]
____
Before the 1950s candidate could file the necessary paperwork in any court from the federal
level down to the local level. Thus, researchers looking for naturalization records must be
aware of the categories of naturalization records and where they are located. Currently in
Indiana, naturalization records fall into two categories: **naturalization proceeding notes
in court order books, which are notes abiyt court proceedings jotted don by court clerks and
which indexed in this volume;** and "naturalization documents", which are manuscript items
such as forms, certificates, and bound naturalization books, which are located at the Indiana
State Archives.
____

_An Index to Naturalization Record in pre-1907 Order Books of Indiana County Courts_


