= Miscellaneous Military

[caption="Sources for: "]
.Adams county, Indiana
[cols="1,3",%header,frame="none",grid="rows"]
|===
|Location|Description(Link)

|Genealogy Center|Book about Adams county soldiers during Civil War link:https://acpl.na4.iiivega.com/search?query=31924966[The citizen soldier]
|===

.Email first email exchange with Charles Luttman
[quote, charles luttmann 1:31 PM (55 minutes ago) to me]
____

I have his father listed as Johann Heinrich Christian Fehls married to Maria Sophie Kleinschmidt. Fred also had a brother,
Christian Fehls (Fells) who was drafted and placed in the 51st Indiana Infantry company D. After the war he moved to
Nebraska.  Sent from my iPhone

On Oct 2, 2024, at 10:22 AM, kurt krueckeberg <kurt.krueckeberg@gmail.com> wrote:

A Christian Wilhelm Fells was one one of the Founders of Immanuel Lutheran, Decatur, although there is no church biography
for him. Some of the founders later moved elsewhere like Hebron Nebraska, where Andreas Thieme and his 2nd wife moved. The
biographies were not written, I don't think, at the founding of the church was at a later day, when some of them have already
moved away. 

That was actually fascinating about the encounter with Abraham Lincoln. I have to try to hunt down that article. Thanks for
the feedback.

Kurt
____ 

.2nd Email exchange with Charles Luttman
[quote, reply from Charles]
____
Greetings, Good to hear from you! All is well here. Thanks for the information. I'll look into getting a copy of this book
through my library. I'm currently researching Johann Friedrich Fehls. During and after the Civil War he became known as
Frederick Fells or Fred Fells. He is a second cousin 3xremoved. His mother was a Kleinschmidt. He enlisted in the 1st Indiana
Cavalry Company K (also known as Brackens Rangers). He had an interesting encounter with Abe Lincoln on the evening of
October 2, 1862 and the following morning of October 3, 1862. There is an article in the May 28, 1911 edition of the
Indianapolis Star where he describes the incident in detail. Very interesting!

Charles
____


