= Transliteration of Heinrich Wilhelm Weiland's LAst Will & Testament

 xref:attachment$heinrich_wilhelm_weiland_will.jpg[here].

Ich Wilhelm Weiland mache heirmit meinen
Letzten Willen und Testament
[Meinen?] Seele  ich den lebendigen Gott
und meinen Leib der zur seligen...
den Todten. Mit Meinens
[??? [??] ich [??] es folgendes [???] [???] nach meinen Ableben
meinden soll:

meinen ältesten Sohn Kahrl Heinrich Wilhem
Weiiland vermache ich die |40| fiezig Acker in Secktion 28
meiner Ehefrau Sophie Wilhelmine Christine gebÖ
[Fiel]

Ableben ……………… mit meines 
Un  scheiht bekentlige

Be it known John H. Krückeberg
one of the subscribing winesses of the last will and testament
of Henry W. Weiland, late of Adams County decased,
personally appeared before the undersigned Clerk of
the Adams Circuit County of Adams County being of
lawful age and being by me only sworn deposed
as follows: That Henry W. Weiland deceased on the 5th
day of September 1874 that he left the foregoing as his
last will and testament, that the undersigned was pres-
sent and saw the said testator sign hi name to the same
and he also published and declared that the same was
his last will and testament: that he was of sound
mind and meory, fully compettent to devise his prop-
erty and was unde no restaint or coercision whatever.


That John H. Kruecckeberg. G/ W/ Felz

